### ISSUE TITLE
Additional Commands

### ISSUE THREAD

**Issue by sam-jeffs** [bitfocus/companion-module-disguise#1]
Hi,

would be great if additional OSC commands could be added, here's a list of a few that would be great:

track id: /d3/showcontrol/trackid
track name: /d3/showcontrol/trackname
return to start: /d3/showcontrol/returntostart
previous track: /d3/showcontrol/previoustrack
next track: /d3/showcontrol/nexttrack
volume(value from 0-1): /d3/showcontrol/volume
brightness (value from 0-1: /d3/showcontrol/brightness

That would then complete the list of the default available options.

Also the first time i've delved into github so if this isnt the right place then please let me know where to go!

**Comment by willosof** [comment]
Correct place!

**Comment by willosof** [comment]
Previous track and next track should already be there?

**Comment by sam-jeffs** [comment]
Apologies yes they are!

**Comment by willosof** [comment]
track id wants an integer and trackname wants a string?

**Comment by sam-jeffs** [comment]
Integer and string: as you say

Actions: Go to

**Comment by willosof** [comment]
Available for testing in build 1457 (build ready in about 10 minutes)

**Comment by willosof** [comment]
Closing this when you're done testing it!

**Comment by sam-jeffs** [comment]
Will do, thanks!

**Comment by sam-jeffs** [comment]
Should it be build 1466? I've installed that but can't see any additional options.

**Comment by willosof** [comment]
Try 1467
