### ISSUE TITLE
disguise Module: Add Hold function

### ISSUE THREAD

**Issue by MarcusGarfunkel** [bitfocus/companion-module-disguise#2]
Describe the feature
Please add the "Hold" function

Is this platform dependent (windows, mac, ..)?
I believe not, although only tested on Windows.

If documentation is required to implement, do you know where to find it?
Here: "/d3/showcontrol/hold"

Usecases
"hold" freezes the disguise outputs, so it is a very handy function.

**Comment by JeffreyDavidsz** [comment]
Added function, does this need a unhold?

**Comment by MarcusGarfunkel** [comment]
An unhold function is not necessary. "Fade up" is the equivalent to "unhold" in this case.
